# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

dist: ./.dist

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    binary: hermaeus-operator
    flags:
      - -v
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -X github.com/hermaeus-project/hermaeus-operator/common.version={{ .Version }}
      - -X github.com/hermaeus-project/hermaeus-operator/common.buildDate={{ .Date }}
      - -extldflags="-static"

dockers:
  - image_templates: &images
      - ghcr.io/hermaeus-project/hermaeus-operator:{{ .Tag }}
      - ghcr.io/hermaeus-project/hermaeus-operator:latest
      # - ghcr.io/hermaeus-project/hermaeus-operator:v{{ .Major }}
      # - ghcr.io/hermaeus-project/hermaeus-operator:v{{ .Minor }}
    skip_push: "{{ .IsSnapshot }}"
    use: buildx
    goarch: amd64
    dockerfile: ./Dockerfile.release
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: ghcr.io/hermaeus-project/hermaeus-operator:{{ .Tag }}
    image_templates:
      - ghcr.io/hermaeus-project/hermaeus-operator:{{ .Tag }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github
  sort: asc
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: "Dependency updates"
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: "Other work"
      order: 999
  filters:
    exclude:
      - "^test:"
      - '^.*?Bump(\([[:word:]]+\))?.+$'

release:
  name_template: "{{.ProjectName}}-{{.Tag}}"
  skip_upload: "{{ .IsSnapshot }}"
  prerelease: auto
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
