# This rule is not used by the project hermaeus-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to doc.hermaeus.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hermaeus-operator
    app.kubernetes.io/managed-by: kustomize
  name: document-viewer-role
rules:
- apiGroups:
  - doc.hermaeus.io
  resources:
  - documents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - doc.hermaeus.io
  resources:
  - documents/status
  verbs:
  - get
