name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codegen:
    name: Check Codegen
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: go mod tidy
        run: |
          go mod tidy
          if ! diff=$(git diff --exit-code --unified=0 -- go.sum); then
            line=$(echo "$diff" | sed -nr 's/@@ -([0-9]+),.*/\1/p' | head -n 1 | tr -d '\n')
            echo "::error file=go.sum,line=$line::go.sum is out of date. Run 'go mod tidy' and commit the changes."
            exit 1
          fi

      - name: make build-installer
        run: |
          make build-installer
          if ! git diff --exit-code; then
            echo "::error ::Manifests are out of date. Run 'make build-installer' and commit the changes."
            exit 1
          fi

      - name: make build-helm-chart
        run: |
          make build-helm-chart
          if ! git diff --exit-code; then
            echo "::error ::Manifests are out of date. Run 'make build-helm-chart' and commit the changes."
            exit 1
          fi

  test:
    name: Tests
    needs:
      - codegen
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

      - name: Running Tests
        run: |
          go mod tidy
          make test

      # - name: Build
      #   if: steps.cache-build.outputs.cache-hit != 'true'
      #   run: make
      # - name: Run Integration Tests
      #   run: make test-parallel

      # - name: Generate code coverage artifacts
      #   if: ${{ !cancelled() }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage
      #     path: cover.out

      # - name: Upload code coverage information to codecov.io
      #   if: ${{ !cancelled() }}
      #   uses: codecov/codecov-action@v5.4.3
      #   with:
      #     files: cover.out
      #     fail_ci_if_error: false
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # - name: Upload test results to codecov.io
      #   if: ${{ !cancelled() }}
      #   uses: codecov/test-results-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

  test-e2e:
    name: End to end tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - test
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e

  test-chart:
    name: Chart test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - test-e2e
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Prepare hermaeus-operator
        run: |
          go mod tidy

          # Tag must be different than "latest" to change imagePullPolicy to "IfNotPresent"
          # See `kubectl explain pod.spec.containers.imagePullPolicy`
          make docker-build IMG=local/hermaeus-operator:dev
          kind load docker-image local/hermaeus-operator:dev

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Lint Helm Chart
        run: |
          helm lint ./dist/chart

      # TODO: Uncomment if cert-manager is enabled
      #      - name: Install cert-manager via Helm
      #        run: |
      #          helm repo add jetstack https://charts.jetstack.io
      #          helm repo update
      #          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true
      #
      #      - name: Wait for cert-manager to be ready
      #        run: |
      #          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager
      #          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-cainjector
      #          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-webhook

      # TODO: Uncomment if Prometheus is enabled
      #      - name: Install Prometheus Operator CRDs
      #        run: |
      #          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      #          helm repo update
      #          helm install prometheus-crds prometheus-community/prometheus-operator-crds
      #
      #      - name: Install Prometheus via Helm
      #        run: |
      #          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      #          helm repo update
      #          helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
      #
      #      - name: Wait for Prometheus to be ready
      #        run: |
      #          kubectl wait --namespace monitoring --for=condition=available --timeout=300s deployment/prometheus-server

      - name: Install Helm chart for project
        run: |
          helm install my-release ./dist/chart --create-namespace --namespace hermaeus-operator-system \
            --set controllerManager.container.tag=dev \
            --set controllerManager.container.repo=local/hermaeus-operator

      - name: Check Helm release status
        run: |
          helm status my-release --namespace hermaeus-operator-system

# TODO: Uncomment if prometheus.enabled is set to true to confirm that the ServiceMonitor gets created
#      - name: Check Presence of ServiceMonitor
#        run: |
#          kubectl wait --namespace hermaeus-operator-system --for=jsonpath='{.kind}'=ServiceMonitor servicemonitor/hermaeus-operator-controller-manager-metrics-monitor
